server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogsss
      __path__: /var/log/*.log
- job_name: Nginx
  static_configs:
  - targets:
      - localhost
    labels:
      job: NginxLogs
      __path__: /var/log/nginx/*.log
